### ISSUE TITLE
[QUESTION] Example for install-steps configuration?

### ISSUE THREAD

**Issue by ducrot** [helhum/typo3-config-handling#11]
Is there any doc or example about using install-steps with config/setup/install.steps.yaml? 

[config/install.settings.yaml](https://github.com/helhum/TYPO3-Distribution/blob/master/config/install.settings.yaml) from helhum/TYPO3-Distribution seems outdated.

Thanks!
Christian

**Comment by helhum** [comment]
Have a look at https://github.com/helhum/TYPO3-Distribution/blob/b75fa577a7592023c6c305356b0ffbe6c7ce5f49/config/setup/install.steps.yaml

If you have further questions, let me know.
