### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Patta** [helhum/typo3-config-handling#14]
TYPO3 9.5.15
PHP 7.3.16
Composer mode
Win10 local
typo3-config-handling v1.0.0-BETA9

TYPO3 Exception:
Return value of Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration::getAllSiteConfigurationFromFiles() must be of the type array, null returned

```
Fri, 17 Apr 2020 16:00:11 +0200 [CRITICAL] request="e1f2dad4c0725" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration::getAllSiteConfigurationFromFiles() must be of the type array, null returned | TypeError thrown in file REMOVED\vendor\helhum\typo3-config-handling\src\Typo3SiteConfiguration.php in line 68. Requested URL: https://REMOVED.localhost/typo3/ - {"TYPO3_MODE":"BE","exception":{}}
Fri, 17 Apr 2020 16:02:14 +0200 [CRITICAL] request="a089a20a9eedb" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration::getAllSiteConfigurationFromFiles() must be of the type array, null returned | TypeError thrown in file REMOVED\vendor\helhum\typo3-config-handling\src\Typo3SiteConfiguration.php in line 68. Requested URL: https://REMOVED.localhost/ - {"TYPO3_MODE":"FE","exception":{}}
```

**Comment by infabo** [comment]
https://github.com/helhum/typo3-config-handling/blob/master/src/Typo3SiteConfiguration.php#L67

Yes, this happens because not all cache-backends return `false`. `NullBackend` for example. So Maybe not check for `false` only. Maybe `empty()` would be better.

**Comment by infabo** [comment]
The reason why @helhum implemented is to be v10 compatible - but it is not backwards-compatible with v9.

https://github.com/TYPO3/TYPO3.CMS/blob/7b919798c8784ba3a3dd8cb82ab2d8a7e777878a/typo3/sysext/core/Classes/Cache/Backend/NullBackend.php#L130

v10 NullBackend returns false - in v9 it does not do that.

**Comment by echavaillaz** [comment]
It can be fix easilly.

Just replace `if ($siteConfiguration !== false` with `if ($siteConfiguration !== false && $siteConfiguration !== null)` on line 67 of the file `Typo3SiteConfiguration.php`

Thanks

**Comment by helhum** [comment]
> v10 NullBackend returns false - in v9 it does not do that.

Good catch. I would consider this a bug in v9

**Comment by helhum** [comment]
> Just replace if ($siteConfiguration !== false with if ($siteConfiguration !== false && $siteConfiguration !== null) on line 67 of the file Typo3SiteConfiguration.php

Yeah, I think this is a reasonable fix, until TYPO3 is fixed

**Comment by helhum** [comment]
Anyone of you willing to do a pull request? That would be awesome!

**Comment by echavaillaz** [comment]
I can make it but now not. monday.
