### ISSUE TITLE
Imports with wildcard/glob not working as expected

### ISSUE THREAD

**Issue by colorcube** [helhum/typo3-config-handling#17]
- TYPO3 9.5.18
- typo3-config-handling rc2 (was the same behavior in beta)
- Setup based on TYPO3-Distribution

In the default config/settings.yaml from the distribution there's this line

`- { resource: 'includes/*.yaml', type: glob }`

but it seems that has no effect. Adding config or new files in includes/ are ignored.

On the other hand following works as expected (with or without 'type: glob')

```
    - { resource: 'includes/crontab.yaml' }
    - { resource: 'includes/extension.yaml', type: glob }
```

But adding the wildcard import like this

```
    - { resource: 'includes/crontab.yaml' }
    - { resource: 'includes/extension.yaml', type: glob }
    - { resource: 'includes/*.yaml', type: glob }
```

removes all config imported crontab.yaml and extension.yaml (or both are ignored again).

**Comment by helhum** [comment]
> but it seems that has no effect. Adding config or new files in includes/ are ignored

Can it be that you test with `TYPO3_CONTEXT` being `Production`? In production context, configuration is cached without further checks on changes in the `config` folder

**Comment by colorcube** [comment]
No it's Development and changes in config has immediate effect.
If it's working for you I'll check my setup again.

**Comment by colorcube** [comment]
The problem was an unused file in includes/ with only one line in it:

```
EXTCONF:
```

including this line wiped EXTCONF config from other files.

Adding one key fixes that problem:

```
EXTCONF:
    abc:
```

**Comment by helhum** [comment]
Thanks. Will check why this is the case. Thanks

**Comment by helhum** [comment]
> The problem was an unused file in includes/ with only one line in it:

Thing is that

```yaml
EXTCONF:
```

evaluates to:
```php

[
	'EXTCONF => null,
]
```

and this of course swipes any array previously set.

Can't really do something about this though. What would help is, if TYPO3 had a validation for configuration, which it hasn't.
