### ISSUE TITLE
Minimum composer version requirement missing

### ISSUE THREAD

**Issue by smichaelsen** [helhum/typo3-config-handling#29]
The `install:generatepackagestates` console command fails in my CI with 

```
Fatal error: Uncaught Error: Call to undefined method Composer\InstalledVersions::getInstallPath() in /project-path/vendor/helhum/typo3-config-handling/src/ConfigReader/Typo3BaseConfigReader.php:38
```

On my machine however it works. I suspect it's the composer version. Locally I have tested versions 2.1.3 and 2.1.11. In my CI where it fails I have a 2.0.11.

I'll update the composer version in my CI worker image to resolve this. Is there a way this package can declare its minimum composer version requirement?

**Comment by helhum** [comment]
> The `install:generatepackagestates` console command fails in my CI with
> 
> ```
> Fatal error: Uncaught Error: Call to undefined method Composer\InstalledVersions::getInstallPath() in /project-path/vendor/helhum/typo3-config-handling/src/ConfigReader/Typo3BaseConfigReader.php:38
> ```
> 
> On my machine however it works. I suspect it's the composer version. Locally I have tested versions 2.1.3 and 2.1.11. In my CI where it fails I have a 2.0.11.
> 
> I'll update the composer version in my CI worker image to resolve this. Is there a way this package can declare its minimum composer version requirement?

Yes and the dependency is declared here: https://github.com/helhum/typo3-config-handling/blob/9f04af5cd6836483a3151a56e6449827260ed98f/composer.json#L14

So my question is: How did you mange to install the latest version of this package with an old Composer version?

**Comment by smichaelsen** [comment]
> How did you mange to install the latest version of this package with an old Composer version?
Easy. I used `--ignore-platform-reqs`.

🤦‍♂️ I guess that explains it. Sorry for bothering. 🙏
