### ISSUE TITLE
Exception when importing DefaultConfiguration (8.7.10)

### ISSUE THREAD

**Issue by mkarulin** [helhum/typo3-config-handling#4]
- { resource: 'DefaultConfiguration', type: typo3, exclude: [LOG] }

 leads to a following error:

Uncaught TYPO3 Exception
#1497466197: The config options "SYS/no_pconnect, SYS/dbClientCompress, SYS/setDBinit" have been removed, but remove support is not yet implemented in helhum/typo3-config-handling. Remove these options manually from your configuration. (More information)

RuntimeException thrown in file
/var/www/html/vendor/helhum/typo3-config-handling/src/Xclass/ConfigurationManager.php in line 72.

**Comment by helhum** [comment]
Hi @mkarulin,

the error you are seeing is unrelated to `{ resource: 'DefaultConfiguration', type: typo3, exclude: [LOG] }`

You see this error most likely in TYPO3 install tool, which removes options from `LocalConfiguration.php` that are not supported any more.

In your case the settings `SYS/no_pconnect, SYS/dbClientCompress, SYS/setDBinit` shall be removed, which you have obviously set in your configuration.

To further help, I would need some more information like  a full backtrace of the exception

**Comment by mkarulin** [comment]
But `SYS/no_pconnect, SYS/dbClientCompress, SYS/setDBinit` are only defined in  `typo3/sysext/core/Configuration/DefaultConfiguration.php` ? Why would the install tool throw an uncaught exception?

**Comment by helhum** [comment]
Ok, got it, thanks. Ran into this as well. Fix is incoming

**Comment by helhum** [comment]
It is fixed for me now. Please check if it is fixed as well for you with 0.4.3

**Comment by mkarulin** [comment]
IT seems to be working now. Thank you 👍
