### ISSUE TITLE
Surf deployment created cached Configuration in AdditionalConfiguration

### ISSUE THREAD

**Issue by the-coding-owl** [helhum/typo3-config-handling#5]
I integrated the typo3-config-handling within my new surf deployment script and ran into an issue I do not know how to work around properly.
First I observed that surf is doing the composer install command with --no-dev, which triggers the typo3-config-handling to dump the configuration from YAML into the AdditionalConfiguration.php. So far, this isn't an issue, because I do not integrate any credentials in those YAML files. I added a deployment task to symlink the credentials from a shared configuration on the target server into the releases by replacing the empty LocalConfiguration.php with a LocalConfiguration.php filled with the credentials for the target server. Now my problem begins to take shape,typo3-config-handling dumps the generated configuration as 
`return [ /* the configuration array */ ];` and not with array_merge or something, so it will overwrite everything specified in LocalConfiguration.php.
I do not want to have every deployment client know the credentials of the target server, when a deployment is made, but I still like the dumping of the configuration with --no-dev in composer install.
The question is, could there be an array_merge integrated into the dumped configuration, so configuration made inside the LocalConfiguration.php isn't overridden by it?
Or do you suggest another way of handling credentials with typo3-config-handling and surf deployment?

**Comment by helhum** [comment]
Hey,

if you decide to use typo3-config-handling, then you decide to give up ownership of both LocalConfiguration.php and AdditionalConfiguration.php. Both are then handled by this package.

To handle configuration specific to an environment, either use .env, put some options directly in the environment or provide some host config file on deployment

In my [distribution]((https://github.com/helhum/TYPO3-Distribution/blob/8ed25a538e10eb69dc2407ac031693d752d45170/conf/config.yml#L7)) if conf/host.yml exist, it is evaluated, if not it is ignored. On deployment you can put or link it there and be done.
