### ISSUE TITLE
Override Site Settings in TYPO3 v12+

### ISSUE THREAD

**Issue by infabo** [helhum/typo3-config-handling#56]
Since https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.1/Feature-99047-LoadSiteSettingsFromSeparateSettingsyaml.html it is not possible anymore to override `settings` in Site configuration anymore (when XCLASSED `\Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration` is used).

This is because TYPO3 reads site configuration and then "overlays" it with a dedicated read of `settings.yaml` file.

* v13: https://github.com/TYPO3/typo3/blob/v13.4.1/typo3/sysext/core/Classes/Configuration/SiteConfiguration.php#L119
* v12: https://github.com/TYPO3/typo3/blob/v12.4.23/typo3/sysext/core/Classes/Configuration/SiteConfiguration.php#L154

**Comment by helhum** [comment]
Can you confirm that #57 fixes that?

**Comment by helhum** [comment]
> Can you confirm that #57 fixes that?

@infabo can you confirm this is fixed with the mentioned pr?

**Comment by infabo** [comment]
Thank you! Can verify it is working.
