### ISSUE TITLE
Example setup configuration for community extensions

### ISSUE THREAD

**Issue by robsonrobi** [helhum/typo3-config-handling#6]
First of all, great work. 
Can you give a snippet on how to setup values, that are serialized stored in the LocalConfiguration.php ? For example the path to the real url conf, set i want to use ?
That would be really nice.

Greetings
robsonrobi

**Comment by robsonrobi** [comment]
I think you it is done out of the box :-)

**Comment by helhum** [comment]
Can you elaborate in more detail on what exactly you are trying to achieve? Maybe give an example.

**Comment by robsonrobi** [comment]
We made it yesterday to get it to work, but today with the newest version we only get an auto-generated AdditionalConfiguration.php and not previously used ConfigLoader... ->publish.

In composer.json we just include one file. in that yaml all other yaml files will be included then:

```
"helhum/typo3-config-handling": {
			"main-config": "conf/config.yaml"
		}
```

**Comment by helhum** [comment]
It would be helpful if you could provide a little bit more context. Like what errors you exactly are seeing, how the configuration file looks like and/or how the complete composer.json looks like. 

Also the exact steps you took to include this package might be helpful

**Comment by robsonrobi** [comment]
Yes of course, sorry for the few information.
Let me first explain our goal. :-)

We are switching our development / configuration to ansible. We use ansible to configure the server in the cloud and for local development we will use ansible in combination with vagrant.
For better consistency and a kind of base configuration we want to use your library to setup all necessary information in yaml files. So syncing a live database and filesystem to vagrant will still exist, but WITHOUT syncing the LocalConfiguration.php, AdditionalConfiguration.php and PackageStates.php. The files should be generated through typo3-config-handling.

Process will be:
1. build vagrant box
2. sync project including composer.json and composer.lock into box
3. run composer install and typo3cms command, etc...

The composer.json looks like:

`
{
	"name": "project/xxx",
	"authors": [
		{
			"name": "xxx",
			"email": "yyyy@zzz.de"
		}
	],
	"repositories": [
		{
			"type": "composer",
			"url": "https://composer.typo3.org/"
		},
		{
			"type": "vcs",
			"url": "https://github.com/froemken/repair_translation"
		}
	],
	"minimum-stability": "stable",
	"config": {
		"secure-http": false
	},
	"extra": {
		"typo3/cms": {
			"web-dir": "htdocs",
			"cms-package-dir": "{$vendor-dir}/typo3/cms",
			"prepare-web-dir": true,
			"extension-dir": "{$config-dir}/ext"
		},
		"helhum/typo3-console": {
			"install-extension-dummy": false
		},
		"helhum/typo3-config-handling": {
			"main-config": "conf/config.yaml"
		}
	},
	"scripts": {
	},
	"autoload": {
		"psr-4": {
			"NS\\Myext\\": "htdocs/typo3conf/ext/myext/Classes",
		}
	},
	"require": {
		"typo3/cms-composer-installers": "1.5.2",
		"typo3/cms": "^8.7",
		"helhum/typo3-console": "^5.4",
		"helhum/typo3-config-handling": "^0.7.1",
		"dmitryd/typo3-realurl": "2.3.2",
		"fluidtypo3/vhs": "4.3.2",
		"typo3-ter/mask": "3.1.0",
		"stefanfroemken/repair_translation": "^1.4.0",
		"gridelementsteam/gridelements": "8.2.1",
		"wyrihaximus/html-compress": "^1.2",
		"typo3-ter/additional-reports": "^3.1.0",
		"typo3-ter/t3adminer": "^9.1.0",
		"typo3-ter/error404page": "^3.0.4",
		"georgringer/news": "6.1.1",
		"evoweb/recaptcha": "8.2.0",
		"koninklijke-collective/my-redirects": "3.4.1"
	}
}
`

We only use one config.yaml (see composer.json), where we requiere additional files, that are served via ansible, for example:

`imports:
    - { resource: 'DefaultConfiguration', type: typo3, exclude: [LOG] }
    - { resource: 'extension.yaml', type: glob }
    - { resource: 'cache.vagrant.yaml', type: glob }
    - { resource: 'env.vagrant.yaml', type: glob }

# Reasonable error handling by default
BE:
    explicitADmode: 'explicitAllow'
    loginSecurityLevel: 'rsa'
    compressionLevel: 5
    flexformForceCDATA: true
    versionNumberInFilename: true
    lockSSL: false
`

Questions came up:
1. Do we need the all settings described in your readme ?
`"main-config": "config/settings.yaml",
  "prod-config": "config/prod.settings.yaml",
   "dev-config": "config/dev.settings.yaml",
   "ext-config": "config/includes/extension.yaml"
`
2. Currently the AdditionalConfiguration.php is very big. The array defaultPageTSconfig did i never realize inside the previous used LocalConfiguration.php Are these values really necessary and where did they come from ?

3. If we add a new property to config.yaml, how do we invalidate the resulting AdditionalConfiguration.php ? As i understand, we have some kind of dev mode (version with ->publish() inside the AdditionalConfiguration.php) and a cached version. That is definetely the most important part for us.

4. What will happen, if a new TYPO3 8.x Version defines new values for the LocalConfiguration.php and sets for example some default values. To be precise we need to fetch these new values and define them in our yaml to be consistent, right?

I really like your library and i am looking forward to hear from you.

Thanks
robsonrobi

**Comment by robsonrobi** [comment]
Any advice?

**Comment by robsonrobi** [comment]
I think, i got it.
