### ISSUE TITLE
[QUESTION] What's the exact purpose of "ext-config"?

### ISSUE THREAD

**Issue by p2media** [helhum/typo3-config-handling#7]
Hi!

My `composer.json` looks like this:
```
{
    "extra": {
        "helhum/typo3-config-handling": {
            "main-config": "config/settings.yaml",
            "prod-config": "config/settings.production.yaml",
            "dev-config": "config/settings.development.yaml",
            "ext-config": "config/settings.extension.yaml"
        }
    }
}
```

When using `typo3cms settings:extract` the `config/settings.extension.yaml` will be populated with my "old" configuration as aspected. 
I thought that this file for extension configuration will be imported automatically, but it won't.

For now I had to import the `config/settings.extension.yaml` inside the `config/settings.yaml` file manually

I want to ask you if you can explain the `ext-config` a bit more.  
Is this the intended behaviour and I misunderstood this feature or is this a bug?

Thanks in advance!

**Comment by p2media** [comment]
Yeah, it helped me.  
But I still need to import `config/settings.extension.yaml` in `config/settings.yaml`, if I understand you correctly.

**Comment by helhum** [comment]
> But I still need to import config/settings.extension.yaml in config/settings.yaml, if I understand you correctly

Yes, exactly.
